name: Build QuickPocket APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.22.3'
      
      - name: Fix Android Folder
        run: |
          rm -rf android
          flutter create . --platforms=android --project-name quickpocket
      
      - name: Get dependencies
        run: flutter pub get
      
      - name: Build APK Debug
        run: flutter build apk --debug --no-tree-shake-icons
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: QuickPocket-OPay-8111275146-APK
          path: build/app/outputs/flutter-apk/app-debug.apk

   
